### PR TITLE
Replace default boot logo with UTM logo

### PR DESCRIPTION
**Pull request by conath**

### CODE REVIEW

**Comment by conath** [comment]
I'm currently building this for AARCH64 and X64.

**Comment by conath** [comment]
Here are the EFI images for AARCH64 and X64:
[edk2-utmlogo-AARCH64_and_X64.zip](https://github.com/utmapp/edk2/files/6380560/edk2-utmlogo-AARCH64_and_X64.zip)

**Comment by osy** [comment]
> Here are the EFI images for AARCH64 and X64:
> [edk2-utmlogo-AARCH64_and_X64.zip](https://github.com/utmapp/edk2/files/6380560/edk2-utmlogo-AARCH64_and_X64.zip)

Just to confirm these built binaries contain https://github.com/utmapp/edk2/commit/c8440e1ccccd9790945301e5c137603b8a3ea57b and https://github.com/utmapp/edk2/commit/bca86ecf2e1124c8a931b0dbfc276c7280df35c7 and is based off of the tree at https://github.com/conath/edk2/commits/utm-logo ?

**Comment by conath** [comment]
Yes. They are from that exact branch, and not the ones I made earlier and posted on [chrisp.cafe](https://chrisp.cafe/OVMF/) (in those earlier ones I modified the ramfb resolutions).

**Comment by conath** [comment]
The binaries linked in my previous comment were mistakenly built using DEBUG configuration (the default), when we need the RELEASE one. Using the [edk2 Build Configurations](https://github.com/tianocore/edk2-platforms#build-options) reference, I corrected the build command I used and re-compiled the x64 and AARCH64 EFI binaries:

edk2-release-compile

Build on a Ubuntu Server 20.04.2 x86_64 UTM virtual machine:

For AARCH64: `env GCC5_AARCH64_PREFIX=aarch64-linux-gnu- build -a AARCH64 -t GCC5 -p ArmVirtPkg/ArmVirtQEMU.dsc -b RELEASE`

For X64: `build -a X64 -t GCC5 -p OvmfPkg/OvmfPkgx64.dsc -b RELEASE`

The binaries: 

[edk2-utmlogo-release.zip](https://github.com/utmapp/edk2/files/6523369/edk2-utmlogo-release.zip)

**Pull request merged**
